enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[SoundCloud]
enabled =  true
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud"
build-mode = "apk"

[Twitter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
build-mode = "apk"
dpi = "120-640dpi"
