enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
compression-level = 9
riplib = true

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"

[SoundCloud]
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"
arch = "arm64-v8a"

[Twitter]
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "crimera ReVanced"
